name = "MoWDRO"
uuid = "8370fda5-a5bd-4bd9-827a-39d50e9dacea"
authors = ["Shixuan Zhang"]
version = "1.0.0-DEV"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
