# numerical example for a polynomial regression problem defined by
# min E[F(x,ξ)], x ∈ [-1,1]ⁿ, ξ = (z,v) ∈ Z × ℝ ⊆ ℝᵐ⁺¹,
# where n = (m+d choose d), for the input degree d ≥ 1, and
# F(x,ξ) := (v - ∑ₐ xₐ⋅zᵃ)² is the squared loss function.
# Currently the allowed options for Z are:
# (1) entire space ℝᵐ,
# (2) nonnegative orthant [0,+∞)ᵐ,
# (3) unit box [0,1]ᵐ.
# The samples of z are generated by
# (1) Gaussian(0,Σ), (2) folded Gaussian z->|z|,
# and (3) rescaled Gaussian z->z²/(1+z²),
# and v = g(z) + ϵ for some randomly generated polynomial g of degree d,
# and ϵ is a Gaussian noise with mean 0 and variance σ².

using Distributed
# load modules on the main process
using JuMP, TOML
using LinearAlgebra, DynamicPolynomials, SemialgebraicSets, Statistics
using DataFrames, CSV
using Gurobi, Mosek, MosekTools
using MoWDRO
const GRB_ENV = Gurobi.Env()
# load modules on the worker processes
let
    setup_expr = quote
        using JuMP
        using LinearAlgebra, DynamicPolynomials, SemialgebraicSets
        using Gurobi, Mosek, MosekTools
        using MoWDRO
        const GRB_ENV = Gurobi.Env()
    end
    for w in workers()
        w == myid() && continue
        remotecall_wait(w) do
            Base.eval(Main, setup_expr)
        end
    end
end

include(joinpath(@__DIR__, "..", "..", "experiment_common.jl"))
CONFIG_PATH = resolve_config_path(@__FILE__)
CONFIG      = TOML.parsefile(CONFIG_PATH)

# bind experiment-wide settings from [experiment]
const EXP_CFG = CONFIG["experiment"]
SEED           = apply_random_seed!(EXP_CFG)
TRAIN_SIZES    = parse_train_sizes(EXP_CFG)
TEST_SIZE      = Int(EXP_CFG["testing sample size"])
OPT_GAP        = Float64(EXP_CFG["target optimality gap"])
MIN_AUX        = Float64(EXP_CFG["Wasserstein dual min"])
MAX_AUX        = Float64(EXP_CFG["Wasserstein dual max"])
MIN_PHI        = Float64(EXP_CFG["loss lower bound"])
MAX_CUT_COEF   = Float64(EXP_CFG["maximum cut coefficient"])
BASELINE       = String(get(EXP_CFG, "baseline method", "none"))
RADIUS_SCALING = Int(get(EXP_CFG, "radius scaling", 0))
WASS_ORDER     = Int(EXP_CFG["Wasserstein order"])
NUM_REPS       = parse_num_reps(EXP_CFG)
WASS_RADII     = parse_wass_radii(EXP_CFG)

# bind problem-specific settings from [problem]
const PROB_CFG = CONFIG["problem"]
NUM_VAR     = Int(PROB_CFG["number of variables"])
DEG_POLY    = Int(PROB_CFG["truth polynomial degree"])
NOISE_SIGMA = Float64(PROB_CFG["noise standard deviation"])
SUPPORT_SET = String(PROB_CFG["support set"])
SPARSE_PROB = Float64(PROB_CFG["probability for sparsity"])
LOSS_TYPE      = String(get(PROB_CFG, "regression type", "mean"))
QUANTILE_LEVEL = Float64(get(PROB_CFG, "quantile level", 0.5))

OUTPUT_FILE = resolve_output_file(
    LOSS_TYPE == "quantile" ?
        "result_regression_$(NUM_VAR)_$(DEG_POLY)_pinball_tau" *
            replace(string(QUANTILE_LEVEL), "." => "p") * ".csv" :
        "result_regression_$(NUM_VAR)_$(DEG_POLY).csv"
)

# helper function to generate multiindices of n variables up to degree d
function multiindices(n, d)
    indices = Vector{NTuple{n, Int}}()
    function recurse(prefix, remaining, slots)
        if slots == 1
            push!(indices, Tuple([prefix...; remaining]))
        else
            for a in remaining:-1:0
                recurse([prefix...; a], remaining - a, slots - 1)
            end
        end
    end
    for k in 0:d
        recurse(Int[], k, n)
    end
    return indices
end

# function that conducts experiments on the polynomial regression examples
function experiment_regression(
        m::Int,                                     # regressor dimension
        d::Int,                                     # polynomial degree
        σ::Float64,                                 # noise standard deviation
        wass_radii::Vector{Float64},                # Wasserstein radii to sweep
        wass_order::Int,                            # shared Wasserstein order (p)
        train_sizes::Vector{Int} = TRAIN_SIZES,     # list of training-sample sizes to sweep
        test_size::Int = TEST_SIZE;                 # number of testing samples
        Σ::Matrix{Float64} = zeros(0,0),            # covariance of sample generation
        support_set::String = SUPPORT_SET,          # support set Z; see options below
        sparse_prob::Float64 = SPARSE_PROB,         # probability of zeroing a ground-truth coefficient
        baseline::String = BASELINE,                # baseline method to compare against
        radius_scaling::Int = RADIUS_SCALING,       # s in r/(N/N_min)^(1/s); s ≤ 0 disables scaling
        num_reps::Int = NUM_REPS,                   # number of independent replications
        loss_type::String = LOSS_TYPE,              # "mean" (squared loss) or "quantile" (pinball loss)
        quantile_level::Float64 = QUANTILE_LEVEL,   # τ ∈ (0,1) — only used when loss_type = "quantile"
    )
    baseline in ("none", "noncvx") || error(
        "baseline must be one of \"none\", \"noncvx\"; got \"$baseline\""
    )
    support_set in ("full-space", "orthant", "box") || error(
        "support set must be one of \"full-space\", \"orthant\", \"box\"; got \"$support_set\""
    )
    loss_type in ("mean", "quantile") || error(
        "regression type must be one of \"mean\", \"quantile\"; got \"$loss_type\""
    )
    (loss_type == "quantile" && !(0.0 < quantile_level < 1.0)) && error(
        "quantile level must lie strictly in (0,1); got $quantile_level"
    )
    isempty(train_sizes) && error("training sample sizes array must be non-empty")
    # randomly generate a covariance matrix if not supplied
    if size(Σ) != (m,m)
        L_Σ = rand(m,m)
        Σ = L_Σ'*L_Σ
        Σ /= norm(Σ)
    end
    # randomly generate the ground truth polynomial
    @polyvar z[1:m]
    truth = 0
    A = multiindices(m,d)
    for α in A
        truth += Int(rand()>sparse_prob) * (2*rand()-1) * prod(z[i]^α[i] for i in 1:m)
    end
    # take the samples of the uncertainty (draw the largest training set once,
    # then later iterations reuse a strict prefix of it)
    transform_sample = if support_set == "full-space"
        z->z
    elseif support_set == "orthant"
        z->abs.(z)
    elseif support_set == "box"
        z->(z.^2)./(1 .+ z.^2)
    end
    augment_sample = z -> [transform_sample(z); truth(transform_sample(z))+randn()*σ]
    # pre-draw one full N_max-sized training set per replication so each
    # rep gets independent training data while all per-rep slices of size
    # N share the same prefix.
    N_max = maximum(train_sizes)
    sample_train_full_per_rep = [
        map(augment_sample, [cholesky(Σ).L * randn(m) for _ in 1:N_max])
        for _ in 1:num_reps
    ]
    sample_test = map(augment_sample, [cholesky(Σ).L * randn(m) for _ in 1:test_size])
    # define the loss function
    n = length(A)
    @polyvar x[1:n] ξ[1:(m+1)] # ξ = (z,v)
    residual = ξ[m+1] - sum(x[i] * prod(ξ[j]^A[i][j] for j in 1:m) for i in 1:n)
    Ξ = basicsemialgebraicset(FullSpace(), if support_set == "orthant"
                                    [ξ[i] + 0.0 for i in 1:m]
                                elseif support_set == "box"
                                    [[ξ[i]*(1-ξ[i]) for i in 1:m];
                                     [ξ[i] for i in 1:m];
                                     [1-ξ[i] for i in 1:m]]
                                end)
    # squared loss for mean regression, or pinball loss ρ_τ(residual) =
    # max(τ·residual, (τ-1)·residual) rewritten as the max of two polynomials
    # so that the max-of-polys `SamplePolynomialLoss` path handles it.
    loss = if loss_type == "mean"
        F   = residual^2
        ∇ₓF = differentiate(F, x)
        SamplePolynomialLoss(x, ξ, F, ∇ₓF, Ξ)
    else # "quantile"
        τ  = quantile_level
        F1 = τ * residual
        F2 = (τ - 1.0) * residual
        SamplePolynomialLoss(x, ξ, [F1, F2],
                             [differentiate(F1, x), differentiate(F2, x)], Ξ)
    end
    # print the problem information
    println("Start the experiment on the polynomial regression problem...")
    println("The regression type is \"", loss_type, "\"",
            loss_type == "quantile" ? " with quantile level τ = $(quantile_level)" : "")
    println("The number of regression parameters is ", n)
    println("The number of regressors is ", m)
    println("Training sample sizes to sweep: ", train_sizes)
    println("Number of testing samples: ", test_size)
    println("The loss function is ",
            loss_type == "mean" ? residual^2 :
                "max(", quantile_level, "·residual, ",
                quantile_level - 1.0, "·residual)")
    println("The ground truth is ", truth)
    println("The noise std is ", σ)
    println("The sample covariance matrix is\n", Σ)
    println()
    # prepare the table for output
    WASS_RAD   = Float64[]
    WASS_DEG   = Int[]
    WASS_IDX   = Int[]
    REP_IDX    = Int[]
    TRAIN_SIZE = Int[]
    TRAIN_OBJ  = Float64[]
    TRAIN_TIME = Float64[]
    TEST_MEAN  = Float64[]
    TEST_STD   = Float64[]
    TEST_MED   = Float64[]
    TEST_Q90   = Float64[]
    TEST_Q10   = Float64[]
    # τ column emitted only for quantile-regression runs; the summarizer
    # uses its presence to relabel plots with the pinball-loss context.
    if loss_type == "quantile"
        QUANTILE_COLUMN = Float64[]
    end
    # nonconvex-baseline outputs (defined only if baseline == "noncvx")
    if baseline == "noncvx"
        NCVX_OBJ   = Float64[]
        NCVX_TIME  = Float64[]
        NCVX_MEAN  = Float64[]
        NCVX_STD   = Float64[]
        NCVX_MED   = Float64[]
        NCVX_Q90   = Float64[]
        NCVX_Q10   = Float64[]
    end
    # loop over all (training-sample size, replication, Wasserstein radius)
    # combinations. `train_sizes` stays outermost so the script works
    # through smaller training sizes to larger ones overall; for each N we
    # cycle through every replication before moving on to the next N.
    N_min = minimum(train_sizes)
    for N in train_sizes
        for rep in 1:num_reps
            println("=== N = $N, replication $rep / $num_reps ===")
            sample_train = sample_train_full_per_rep[rep][1:N]
            for (radius_idx, wass_r) in enumerate(wass_radii)
            # auto-scale the Wasserstein radius by (N/N_min)^(1/s), where
            # s = radius_scaling; s ≤ 0 disables scaling. `radius_idx` is
            # the 1-based position of `wass_r` in the original `wass_radii`
            # list and is preserved as the `WASS_IDX` CSV column so that
            # rows sharing a configured radius can be matched across
            # training-sample sizes even when the actual radius is scaled.
            scaled_r = radius_scaling > 0 ? wass_r / (N / N_min)^(1.0 / radius_scaling) : wass_r
            wassinfo = WassInfo(scaled_r, wass_order)
            # define the main linear optimization problem
            model = Model(() -> Gurobi.Optimizer(GRB_ENV))
            set_attribute(model, "OutputFlag", 0)
            x = @variable(model, -1 <= x[1:n] <= 1, base_name="x")
            w = @variable(model, w >= 0, base_name="w")
            ϕ = @variable(model, ϕ >= 0, base_name="ϕ")
            main = MainProblem(model, x, VariableRef[], w, ϕ, zeros(n), Float64[])
            # set the Wasserstein dual variable feasibility tolerance 
            # relative to the optimality gap
            tol_aux_feas = min(OPT_GAP / (2*wass_r^wass_order), 1)
            # solve the problem
            time_start = time()
            sol = solve_main_level(main,
                                   loss,
                                   sample_train,
                                   wassinfo,
                                   print=1,
                                   opt_gap=OPT_GAP,
                                   max_aux=MAX_AUX,
                                   min_aux=MIN_AUX,
                                   min_phi=MIN_PHI,
                                   max_cut_coef=MAX_CUT_COEF,
                                   tol_aux_feas=tol_aux_feas,
                                   mom_solver=Mosek.Optimizer)
            time_finish = time()
            println("The main problem is solved for Wasserstein radius = ", wassinfo.r,
                    ", training size = ", N)
            println("x = ", sol.x)
            println("f = ", sol.f)
            println("ϕ = ", sol.ϕ)
            println("The training sample objective = ", sol.f+sol.ϕ)
            println("The total computation time is ", time_finish-time_start)
            println("Start the out-of-sample test for the solution...")
            # evaluate the out-of-sample performance
            _, vals = eval_nominal(loss, sol.x, sample_test, details=true)
            println("The testing sample mean = ", mean(vals)+sol.f)
            println("The testing sample standard deviation = ", std(vals))
            # update the output file
            append!(WASS_DEG, wassinfo.p)
            append!(WASS_RAD, wassinfo.r)
            append!(WASS_IDX, radius_idx)
            append!(REP_IDX, rep)
            append!(TRAIN_SIZE, N)
            append!(TRAIN_TIME, time_finish-time_start)
            append!(TRAIN_OBJ, sol.f+sol.ϕ)
            append!(TEST_MEAN, mean(vals)+sol.f)
            append!(TEST_STD, std(vals))
            vec_quant = quantile(vals.+sol.f, [0.1,0.5,0.9])
            append!(TEST_Q10, vec_quant[1])
            append!(TEST_MED, vec_quant[2])
            append!(TEST_Q90, vec_quant[3])
            if loss_type == "quantile"
                append!(QUANTILE_COLUMN, quantile_level)
            end
            # ---------------------------------------------------------------
            # Optional: solve the same instance with the nonconvex global
            # baseline (level bundle with `eval_noncvx_Wass`) at the same
            # Wasserstein radius and record `NCVX_*`.
            if baseline == "noncvx"
                println("Solve the same instance with the nonconvex global baseline...")
                model_NC = Model(() -> Gurobi.Optimizer(GRB_ENV))
                set_silent(model_NC)
                x_NC = @variable(model_NC, 0 <= x_NC[1:n] <= 1, base_name="x_NC")
                w_NC = @variable(model_NC, w_NC >= 0, base_name="w_NC")
                ϕ_NC = @variable(model_NC, ϕ_NC >= 0, base_name="ϕ_NC")
                main_NC = MainProblem(model_NC, x_NC, VariableRef[], w_NC, ϕ_NC, zeros(n), Float64[])
                noncvx_solver = () -> begin
                    opt = Gurobi.Optimizer(GRB_ENV)
                    MOI.set(opt, MOI.RawOptimizerAttribute("NonConvex"), 2)
                    #MOI.set(opt, MOI.RawOptimizerAttribute("MIPGap"), 1e-2)
                    MOI.set(opt, MOI.RawOptimizerAttribute("MIPGapAbs"), 1e-4)
                    #MOI.set(opt, MOI.RawOptimizerAttribute("TimeLimit"), 600)
                    opt
                end
                eval_noncvx_cut = (subproblem, augstate, samples, wassinfo; print=0) ->
                    eval_noncvx_Wass(subproblem, augstate, samples, wassinfo;
                                     noncvx_solver=noncvx_solver, print=print)
                time_start_NC = time()
                sol_NC = solve_main_level(main_NC,
                                          loss,
                                          sample_train,
                                          wassinfo,
                                          print=2, # TODO: disable detailed printing after debugging
                                          opt_gap=OPT_GAP,
                                          max_aux=MAX_AUX,
                                          min_aux=MIN_AUX,
                                          min_phi=MIN_PHI,
                                          cut_evaluator=eval_noncvx_cut)
                time_finish_NC = time()
                println("  Nonconvex baseline x          = ", sol_NC.x)
                println("  Nonconvex baseline objective  = ", sol_NC.f + sol_NC.ϕ)
                println("  Nonconvex baseline time       = ", time_finish_NC - time_start_NC)
                _, vals_NC = eval_nominal(loss, sol_NC.x, sample_test, details=true)
                append!(NCVX_OBJ,  sol_NC.f + sol_NC.ϕ)
                append!(NCVX_TIME, time_finish_NC - time_start_NC)
                append!(NCVX_MEAN, mean(vals_NC) + sol_NC.f)
                append!(NCVX_STD,  std(vals_NC))
                vec_quant_NC = quantile(vals_NC .+ sol_NC.f, [0.1, 0.5, 0.9])
                append!(NCVX_Q10, vec_quant_NC[1])
                append!(NCVX_MED, vec_quant_NC[2])
                append!(NCVX_Q90, vec_quant_NC[3])
                println("  Nonconvex baseline test mean  = ", mean(vals_NC) + sol_NC.f)
                println("  Nonconvex baseline test std   = ", std(vals_NC))
            end
            output = DataFrame(:WASS_IDX   => WASS_IDX,
                               :REP_IDX    => REP_IDX,
                               :WASS_DEG   => WASS_DEG,
                               :WASS_RAD   => WASS_RAD,
                               :TRAIN_SIZE => TRAIN_SIZE,
                               :TRAIN_TIME => TRAIN_TIME,
                               :TRAIN_OBJ  => TRAIN_OBJ,
                               :TEST_MEAN  => TEST_MEAN,
                               :TEST_STD   => TEST_STD,
                               :TEST_Q10   => TEST_Q10,
                               :TEST_MED   => TEST_MED,
                               :TEST_Q90   => TEST_Q90)
            if baseline == "noncvx"
                output.NCVX_OBJ  = NCVX_OBJ
                output.NCVX_TIME = NCVX_TIME
                output.NCVX_MEAN = NCVX_MEAN
                output.NCVX_STD  = NCVX_STD
                output.NCVX_Q10  = NCVX_Q10
                output.NCVX_MED  = NCVX_MED
                output.NCVX_Q90  = NCVX_Q90
            end
            if loss_type == "quantile"
                output.QUANTILE_LEVEL = QUANTILE_COLUMN
            end
            CSV.write(OUTPUT_FILE, output)
            println("Update the result in ", OUTPUT_FILE)
            println("\n\n")
            # ensure per-iteration logs reach the terminal in real time —
            # Distributed workers leave the main process with a block-
            # buffered stdout when output is piped or redirected.
            flush(stdout)
            end # close for radius_idx
        end # close for rep
    end # close for N
end

# run the experiment
experiment_regression(NUM_VAR, DEG_POLY, NOISE_SIGMA,
                      WASS_RADII, WASS_ORDER, TRAIN_SIZES, TEST_SIZE;
                      support_set    = SUPPORT_SET,
                      sparse_prob    = SPARSE_PROB,
                      baseline       = BASELINE,
                      radius_scaling = RADIUS_SCALING,
                      num_reps       = NUM_REPS,
                      loss_type      = LOSS_TYPE,
                      quantile_level = QUANTILE_LEVEL)
