# numerical example for a CVaR/superquantile DRO regression problem, derived
# from the Rockafellar-Uryasev reformulation in equation (5.9) of the
# Kuhn-Shafiee-Wiesemann DRO survey (see `claude/DRO_CVaR.pdf`):
#
#   inf_{x, τ}  τ + (1/β) sup_{P ∈ W_r(P̂)} E_P[max(0, L(x, ξ) - τ)],
#
# with ambiguity radius r > 0, level β ∈ (0,1), and squared regression loss
#
#   L(x, ξ) := (v - ∑_a x_a · z^a)^2,   ξ = (z, v) ∈ Z × ℝ ⊆ ℝ^{m+1}.
#
# Absorbing 1/β into the max, the inner integrand is the pointwise maximum
# of two polynomials in the extended decision (x, τ):
#   F1(x, τ, ξ) = 0,
#   F2(x, τ, ξ) = (L(x, ξ) - τ) / β.
# `MainProblem`'s linear objective (via f_x = [zeros(n); 1.0]) carries the
# outer + τ, and `ϕ` approximates the Wasserstein-DRO inner supremum.
#
# Currently the allowed options for Z are:
# (1) entire space ℝᵐ,
# (2) nonnegative orthant [0,+∞)ᵐ,
# (3) unit box [0,1]ᵐ.
# The samples of z are generated by
# (1) Gaussian(0,Σ), (2) folded Gaussian z->|z|,
# and (3) rescaled Gaussian z->z²/(1+z²),
# and v = g(z) + ϵ for some randomly generated polynomial g of degree d,
# and ϵ is a Gaussian noise with mean 0 and variance σ².

using Distributed
# load modules on the main process
using JuMP, TOML
using LinearAlgebra, DynamicPolynomials, SemialgebraicSets, Statistics
using DataFrames, CSV
using Gurobi, Mosek, MosekTools
using MoWDRO
const GRB_ENV = Gurobi.Env()
# load modules on the worker processes
let
    setup_expr = quote
        using JuMP
        using LinearAlgebra, DynamicPolynomials, SemialgebraicSets
        using Gurobi, Mosek, MosekTools
        using MoWDRO
        const GRB_ENV = Gurobi.Env()
    end
    for w in workers()
        w == myid() && continue
        remotecall_wait(w) do
            Base.eval(Main, setup_expr)
        end
    end
end

include(joinpath(@__DIR__, "..", "..", "experiment_common.jl"))
CONFIG_PATH = resolve_config_path(@__FILE__)
CONFIG      = TOML.parsefile(CONFIG_PATH)

# bind experiment-wide settings from [experiment]
const EXP_CFG = CONFIG["experiment"]
SEED           = apply_random_seed!(EXP_CFG)
TRAIN_SIZES    = parse_train_sizes(EXP_CFG)
TEST_SIZE      = Int(EXP_CFG["testing sample size"])
OPT_GAP        = Float64(EXP_CFG["target optimality gap"])
MIN_AUX        = Float64(EXP_CFG["Wasserstein dual min"])
MAX_AUX        = Float64(EXP_CFG["Wasserstein dual max"])
MIN_PHI        = Float64(EXP_CFG["loss lower bound"])
MAX_CUT_COEF   = Float64(EXP_CFG["maximum cut coefficient"])
BASELINE       = String(get(EXP_CFG, "baseline method", "none"))
RADIUS_SCALING = Int(get(EXP_CFG, "radius scaling", 0))
WASS_ORDER     = Int(EXP_CFG["Wasserstein order"])
NUM_REPS       = parse_num_reps(EXP_CFG)
WASS_RADII     = parse_wass_radii(EXP_CFG)

# bind problem-specific settings from [problem]
const PROB_CFG = CONFIG["problem"]
NUM_VAR     = Int(PROB_CFG["number of variables"])
DEG_POLY    = Int(PROB_CFG["truth polynomial degree"])
NOISE_SIGMA = Float64(PROB_CFG["noise standard deviation"])
SUPPORT_SET = String(PROB_CFG["support set"])
SPARSE_PROB = Float64(PROB_CFG["probability for sparsity"])
CVAR_LEVEL  = Float64(PROB_CFG["CVaR level"])
VART_MIN  = Float64(PROB_CFG["VaR threshold lower bound"])
VART_MAX  = Float64(PROB_CFG["VaR threshold upper bound"])

OUTPUT_FILE = resolve_output_file(
    "result_regression_cvar_$(NUM_VAR)_$(DEG_POLY)_beta" *
    replace(string(CVAR_LEVEL), "." => "p") * ".csv"
)

# helper function to generate multiindices of n variables up to degree d
function multiindices(n, d)
    indices = Vector{NTuple{n, Int}}()
    function recurse(prefix, remaining, slots)
        if slots == 1
            push!(indices, Tuple([prefix...; remaining]))
        else
            for a in remaining:-1:0
                recurse([prefix...; a], remaining - a, slots - 1)
            end
        end
    end
    for k in 0:d
        recurse(Int[], k, n)
    end
    return indices
end

# function that conducts CVaR-DRO regression experiments
function experiment_regression(
        m::Int,                                     # regressor dimension
        d::Int,                                     # polynomial degree
        σ::Float64,                                 # noise standard deviation
        β::Float64,                                 # CVaR level β ∈ (0,1)
        wass_radii::Vector{Float64},                # Wasserstein radii to sweep
        wass_order::Int,                            # shared Wasserstein order (p)
        train_sizes::Vector{Int} = TRAIN_SIZES,     # list of training-sample sizes to sweep
        test_size::Int = TEST_SIZE;                 # number of testing samples
        Σ::Matrix{Float64} = zeros(0,0),            # covariance of sample generation
        support_set::String = SUPPORT_SET,          # support set Z; see options below
        sparse_prob::Float64 = SPARSE_PROB,         # probability of zeroing a ground-truth coefficient
        baseline::String = BASELINE,                # baseline method to compare against
        radius_scaling::Int = RADIUS_SCALING,       # s in r/(N/N_min)^(1/s); s ≤ 0 disables scaling
        num_reps::Int = NUM_REPS,                   # number of independent replications
        vart_min::Float64 = VART_MIN,           # lower bound on the β-VaR threshold τ
        vart_max::Float64 = VART_MAX,           # upper bound on the β-VaR threshold τ
    )
    baseline in ("none", "noncvx") || error(
        "baseline must be one of \"none\", \"noncvx\"; got \"$baseline\""
    )
    support_set in ("full-space", "orthant", "box") || error(
        "support set must be one of \"full-space\", \"orthant\", \"box\"; got \"$support_set\""
    )
    isempty(train_sizes) && error("training sample sizes array must be non-empty")
    (0.0 < β < 1.0) || error("CVaR level β must lie strictly in (0,1); got β = $β")
    # randomly generate a covariance matrix if not supplied
    if size(Σ) != (m,m)
        L_Σ = rand(m,m)
        Σ = L_Σ'*L_Σ
        Σ /= norm(Σ)
    end
    # randomly generate the ground truth polynomial
    @polyvar z[1:m]
    truth = 0
    A = multiindices(m,d)
    for α in A
        truth += Int(rand()>sparse_prob) * (2*rand()-1) * prod(z[i]^α[i] for i in 1:m)
    end
    # take the samples of the uncertainty (draw the largest training set once,
    # then later iterations reuse a strict prefix of it)
    transform_sample = if support_set == "full-space"
        z->z
    elseif support_set == "orthant"
        z->abs.(z)
    elseif support_set == "box"
        z->(z.^2)./(1 .+ z.^2)
    end
    augment_sample = z -> [transform_sample(z); truth(transform_sample(z))+randn()*σ]
    # pre-draw one full N_max-sized training set per replication so each
    # rep gets independent training data while all per-rep slices of size
    # N share the same prefix.
    N_max = maximum(train_sizes)
    sample_train_full_per_rep = [
        map(augment_sample, [cholesky(Σ).L * randn(m) for _ in 1:N_max])
        for _ in 1:num_reps
    ]
    sample_test = map(augment_sample, [cholesky(Σ).L * randn(m) for _ in 1:test_size])
    # define the max-of-two-polynomials CVaR loss (per eq. (5.9)):
    #   F(x, τ, ξ) = max(0, (L(x, ξ) - τ)/β).
    n = length(A)
    @polyvar x[1:n] τ ξ[1:(m+1)] # ξ = (z, v); τ is the CVaR auxiliary decision
    L  = (ξ[m+1] - sum(x[i] * prod(ξ[j]^A[i][j] for j in 1:m) for i in 1:n))^2
    F2 = (L - τ) * (1.0 / β)
    F1 = zero(F2)                                   # 0 polynomial of the same type as F2
    Fs   = [F1, F2]
    ∇Fs  = [differentiate(F1, [x; τ]), differentiate(F2, [x; τ])]
    Ξ = basicsemialgebraicset(FullSpace(), if support_set == "orthant"
                                    [ξ[i] + 0.0 for i in 1:m]
                                elseif support_set == "box"
                                    [[ξ[i]*(1-ξ[i]) for i in 1:m];
                                     [ξ[i] for i in 1:m];
                                     [1-ξ[i] for i in 1:m]]
                                end)
    # max-of-two-polys CVaR loss (used only for training)
    loss_train = SamplePolynomialLoss([x; τ], ξ, Fs, ∇Fs, Ξ)
    # plain least-squares loss (used only for out-of-sample evaluation of the
    # recovered x; τ plays no role in test statistics)
    ∇ₓL       = differentiate(L, x)
    loss_test = SamplePolynomialLoss(x, ξ, L, ∇ₓL, Ξ)
    # print the problem information
    println("Start the experiment on the CVaR-DRO polynomial regression problem...")
    println("The number of regression parameters is ", n)
    println("The number of regressors is ", m)
    println("Training sample sizes to sweep: ", train_sizes)
    println("Number of testing samples: ", test_size)
    println("The CVaR level β = ", β)
    println("The VaR threshold bounds are [", vart_min, ", ", vart_max, "]")
    println("The (per-sample) loss branches are")
    println("  F1(x,τ,ξ) = ", F1)
    println("  F2(x,τ,ξ) = ", F2)
    println("The ground truth is ", truth)
    println("The noise std is ", σ)
    println("The sample covariance matrix is\n", Σ)
    println()
    # prepare the table for output
    WASS_RAD    = Float64[]
    WASS_DEG    = Int[]
    WASS_IDX    = Int[]
    REP_IDX     = Int[]
    TRAIN_SIZE  = Int[]
    TRAIN_OBJ      = Float64[]
    TRAIN_TIME     = Float64[]
    TRAIN_VART   = Float64[]
    TEST_MEAN      = Float64[]
    TEST_STD       = Float64[]
    TEST_MED       = Float64[]
    TEST_QLOW      = Float64[]
    TEST_QHIGH     = Float64[]
    TEST_CVAR      = Float64[]
    TEST_CVAR_STD  = Float64[]
    CVAR_COLUMN    = Float64[]
    # nonconvex-baseline outputs (defined only if baseline == "noncvx")
    if baseline == "noncvx"
        NCVX_OBJ      = Float64[]
        NCVX_TIME     = Float64[]
        NCVX_VART   = Float64[]
        NCVX_MEAN     = Float64[]
        NCVX_STD      = Float64[]
        NCVX_MED      = Float64[]
        NCVX_QLOW     = Float64[]
        NCVX_QHIGH    = Float64[]
        NCVX_CVAR     = Float64[]
        NCVX_CVAR_STD = Float64[]
    end
    # loop over all (training-sample size, replication, Wasserstein radius)
    # combinations. `train_sizes` stays outermost so the script works
    # through smaller training sizes to larger ones overall; for each N we
    # cycle through every replication before moving on to the next N.
    N_min = minimum(train_sizes)
    for N in train_sizes
        for rep in 1:num_reps
            println("=== N = $N, replication $rep / $num_reps ===")
            sample_train = sample_train_full_per_rep[rep][1:N]
            for (radius_idx, wass_r) in enumerate(wass_radii)
            # auto-scale the Wasserstein radius by (N/N_min)^(1/s), where
            # s = radius_scaling; s ≤ 0 disables scaling. `radius_idx` is
            # the 1-based position of `wass_r` in the original `wass_radii`
            # list and is preserved as the `WASS_IDX` CSV column so that
            # rows sharing a configured radius can be matched across
            # training-sample sizes even when the actual radius is scaled.
            scaled_r = radius_scaling > 0 ? wass_r / (N / N_min)^(1.0 / radius_scaling) : wass_r
            wassinfo = WassInfo(scaled_r, wass_order)
            # define the main linear optimization problem
            model = Model(() -> Gurobi.Optimizer(GRB_ENV))
            set_attribute(model, "OutputFlag", 0)
            x_reg = @variable(model, -1 <= x_reg[1:n] <= 1, base_name="x")
            τ_var = @variable(model, vart_min <= τ_var <= vart_max, base_name="VaR_threshold")
            w     = @variable(model, w >= 0, base_name="w")
            ϕ     = @variable(model, ϕ >= 0, base_name="ϕ")
            main = MainProblem(model, [x_reg; τ_var], VariableRef[], w, ϕ,
                               [zeros(n); 1.0], Float64[])
            # set the Wasserstein dual variable feasibility tolerance
            # relative to the optimality gap
            tol_aux_feas = min(OPT_GAP / (2*wass_r^wass_order), 1)
            # solve the problem
            time_start = time()
            sol = solve_main_level(main,
                                   loss_train,
                                   sample_train,
                                   wassinfo,
                                   print=1,
                                   opt_gap=OPT_GAP,
                                   max_aux=MAX_AUX,
                                   min_aux=MIN_AUX,
                                   min_phi=MIN_PHI,
                                   max_cut_coef=MAX_CUT_COEF,
                                   tol_aux_feas=tol_aux_feas,
                                   mom_solver=Mosek.Optimizer)
            time_finish = time()
            τ_opt = sol.x[end]
            x_opt = sol.x[1:end-1]
            println("The main problem is solved for Wasserstein radius = ", wassinfo.r,
                    ", training size = ", N)
            println("x = ", x_opt)
            println("τ = ", τ_opt)
            println("f (linear obj at solution = τ) = ", sol.f)
            println("ϕ = ", sol.ϕ)
            println("The training sample objective = ", sol.f+sol.ϕ)
            println("The total computation time is ", time_finish-time_start)
            println("Start the out-of-sample test for the solution...")
            # Out-of-sample: use the plain least-squares loss on the recovered
            # x — τ plays no role in test statistics. `L_test[i] = L(x_opt, ξ̂_i)`
            # is what `eval_nominal(loss_test, ...)` returns as its `vals`.
            _, L_test     = eval_nominal(loss_test, x_opt, sample_test, details=true)
            L_sorted_desc = sort(L_test; rev=true)
            k_tail        = max(1, ceil(Int, β * length(L_test)))
            L_tail        = @view L_sorted_desc[1:k_tail]
            cvar_test     = mean(L_tail)
            cvar_std_test = std(L_tail)
            vec_quant     = quantile(L_test, [β/2, 0.5, 1 - β/2])
            println("The testing sample mean L                     = ", mean(L_test))
            println("The testing sample std  L                     = ", std(L_test))
            println("The testing sample β-CVaR of L                = ", cvar_test, " ± ", cvar_std_test)
            println("The testing sample quantiles at (β/2,0.5,1-β/2) = ", vec_quant)
            # update the output file
            append!(WASS_DEG, wassinfo.p)
            append!(WASS_RAD, wassinfo.r)
            append!(WASS_IDX, radius_idx)
            append!(REP_IDX, rep)
            append!(TRAIN_SIZE, N)
            append!(TRAIN_TIME, time_finish-time_start)
            append!(TRAIN_OBJ, sol.f+sol.ϕ)
            append!(TRAIN_VART, τ_opt)
            append!(TEST_MEAN,  mean(L_test))
            append!(TEST_STD,   std(L_test))
            append!(TEST_QLOW,  vec_quant[1])
            append!(TEST_MED,   vec_quant[2])
            append!(TEST_QHIGH, vec_quant[3])
            append!(TEST_CVAR,     cvar_test)
            append!(TEST_CVAR_STD, cvar_std_test)
            append!(CVAR_COLUMN, β)
            # ---------------------------------------------------------------
            # Optional: solve the same instance with the nonconvex global
            # baseline (level bundle with `eval_noncvx_Wass`) at the same
            # Wasserstein radius and record `NCVX_*`.
            if baseline == "noncvx"
                println("Solve the same instance with the nonconvex global baseline...")
                model_NC = Model(() -> Gurobi.Optimizer(GRB_ENV))
                set_silent(model_NC)
                x_reg_NC = @variable(model_NC, -1 <= x_reg_NC[1:n] <= 1, base_name="x_NC")
                τ_NC     = @variable(model_NC, vart_min <= τ_NC <= vart_max, base_name="VaR_threshold_NC")
                w_NC     = @variable(model_NC, w_NC >= 0, base_name="w_NC")
                ϕ_NC     = @variable(model_NC, ϕ_NC >= 0, base_name="ϕ_NC")
                main_NC  = MainProblem(model_NC, [x_reg_NC; τ_NC], VariableRef[], w_NC, ϕ_NC,
                                       [zeros(n); 1.0], Float64[])
                noncvx_solver = () -> begin
                    opt = Gurobi.Optimizer(GRB_ENV)
                    MOI.set(opt, MOI.RawOptimizerAttribute("NonConvex"), 2)
                    MOI.set(opt, MOI.RawOptimizerAttribute("MIPGap"), 1e-2)
                    MOI.set(opt, MOI.RawOptimizerAttribute("MIPGapAbs"), 1e-3)
                    MOI.set(opt, MOI.RawOptimizerAttribute("TimeLimit"), 600)
                    opt
                end
                eval_noncvx_cut = (subproblem, augstate, samples, wassinfo; print=0) ->
                    eval_noncvx_Wass(subproblem, augstate, samples, wassinfo;
                                     noncvx_solver=noncvx_solver, print=print)
                time_start_NC = time()
                sol_NC = solve_main_level(main_NC,
                                          loss_train,
                                          sample_train,
                                          wassinfo,
                                          print=2, # TODO: disable detailed printing after debugging
                                          opt_gap=OPT_GAP,
                                          max_aux=MAX_AUX,
                                          min_aux=MIN_AUX,
                                          min_phi=MIN_PHI,
                                          cut_evaluator=eval_noncvx_cut)
                time_finish_NC = time()
                τ_opt_NC = sol_NC.x[end]
                x_opt_NC = sol_NC.x[1:end-1]
                println("  Nonconvex baseline x         = ", x_opt_NC)
                println("  Nonconvex baseline τ         = ", τ_opt_NC)
                println("  Nonconvex baseline objective = ", sol_NC.f + sol_NC.ϕ)
                println("  Nonconvex baseline time      = ", time_finish_NC - time_start_NC)
                # out-of-sample: least-squares loss, same convention as the DRO path
                _, L_test_NC        = eval_nominal(loss_test, x_opt_NC, sample_test, details=true)
                L_sorted_desc_NC    = sort(L_test_NC; rev=true)
                L_tail_NC           = @view L_sorted_desc_NC[1:k_tail]
                cvar_test_NC        = mean(L_tail_NC)
                cvar_std_test_NC    = std(L_tail_NC)
                vec_quant_NC        = quantile(L_test_NC, [β/2, 0.5, 1 - β/2])
                append!(NCVX_OBJ,     sol_NC.f + sol_NC.ϕ)
                append!(NCVX_TIME,    time_finish_NC - time_start_NC)
                append!(NCVX_VART,    τ_opt_NC)
                append!(NCVX_MEAN,    mean(L_test_NC))
                append!(NCVX_STD,     std(L_test_NC))
                append!(NCVX_QLOW,    vec_quant_NC[1])
                append!(NCVX_MED,     vec_quant_NC[2])
                append!(NCVX_QHIGH,   vec_quant_NC[3])
                append!(NCVX_CVAR,     cvar_test_NC)
                append!(NCVX_CVAR_STD, cvar_std_test_NC)
                println("  Nonconvex baseline test mean L   = ", mean(L_test_NC))
                println("  Nonconvex baseline test std  L   = ", std(L_test_NC))
                println("  Nonconvex baseline β-CVaR        = ", cvar_test_NC, " ± ", cvar_std_test_NC)
            end
            output = DataFrame(:WASS_IDX      => WASS_IDX,
                               :REP_IDX       => REP_IDX,
                               :WASS_DEG      => WASS_DEG,
                               :WASS_RAD      => WASS_RAD,
                               :TRAIN_SIZE    => TRAIN_SIZE,
                               :TRAIN_TIME    => TRAIN_TIME,
                               :TRAIN_OBJ     => TRAIN_OBJ,
                               :TRAIN_VART  => TRAIN_VART,
                               :TEST_MEAN     => TEST_MEAN,
                               :TEST_STD      => TEST_STD,
                               :TEST_QLOW     => TEST_QLOW,
                               :TEST_MED      => TEST_MED,
                               :TEST_QHIGH    => TEST_QHIGH,
                               :TEST_CVAR     => TEST_CVAR,
                               :TEST_CVAR_STD => TEST_CVAR_STD,
                               :CVAR_LEVEL    => CVAR_COLUMN)
            if baseline == "noncvx"
                output.NCVX_OBJ      = NCVX_OBJ
                output.NCVX_TIME     = NCVX_TIME
                output.NCVX_VART   = NCVX_VART
                output.NCVX_MEAN     = NCVX_MEAN
                output.NCVX_STD      = NCVX_STD
                output.NCVX_QLOW     = NCVX_QLOW
                output.NCVX_MED      = NCVX_MED
                output.NCVX_QHIGH    = NCVX_QHIGH
                output.NCVX_CVAR     = NCVX_CVAR
                output.NCVX_CVAR_STD = NCVX_CVAR_STD
            end
            CSV.write(OUTPUT_FILE, output)
            println("Update the result in ", OUTPUT_FILE)
            println("\n\n")
            # ensure per-iteration logs reach the terminal in real time —
            # Distributed workers leave the main process with a block-
            # buffered stdout when output is piped or redirected.
            flush(stdout)
            end # close for radius_idx
        end # close for rep
    end # close for N
end

# run the experiment
experiment_regression(NUM_VAR, DEG_POLY, NOISE_SIGMA, CVAR_LEVEL,
                      WASS_RADII, WASS_ORDER, TRAIN_SIZES, TEST_SIZE;
                      support_set    = SUPPORT_SET,
                      sparse_prob    = SPARSE_PROB,
                      baseline       = BASELINE,
                      radius_scaling = RADIUS_SCALING,
                      num_reps       = NUM_REPS,
                      vart_min     = VART_MIN,
                      vart_max     = VART_MAX)
