[experiment]
"training sample sweeps"  = [{ start = 20, stop = 200, step = 20 }]
"testing sample size"     = 10000
"target optimality gap"   = 1.0e-4
"Wasserstein dual min"    = 0.0
"Wasserstein dual max"    = 2.0e3
"loss lower bound"        = 0.0
"maximum cut coefficient" = 1.0e4
"baseline method"         = "none"
"radius scaling"          = 4 # same as the number of variables
"random seed"             = "none"  # allowed: integer (e.g. 42) | "none" for fresh random seeding
"Wasserstein order"       = 4
"Wasserstein radii"       = [0.0, 1.0e-2, 5.0e-2, 1.0e-1, 5.0e-1, 1.0]

[problem]
"number of variables"      = 4
"truth polynomial degree"  = 2
"noise standard deviation" = 0.1
"support set"              = "orthant" # options: "full-space", "orthant", or "box"
"probability for sparsity" = 0.5
